FROM python:3.9-slim-buster

RUN apt update -y && apt install -y uvicorn

WORKDIR /app

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./app ./

CMD ["uvicorn", "main:server", "--host", "0.0.0.0", "--port", "8000"]