FROM python:3.9-slim-buster

ENV APP_NAME=api
ENV LABEL=latest

RUN apt update -y && \
    apt install -y uvicorn python3-dev default-libmysqlclient-dev build-essential 

RUN pip install mysqlclient

WORKDIR /app

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir --upgrade -r  ./requirements.txt

COPY ./app ./
COPY ./server_env.json ./server_env.json

RUN mkdir -p /keys

CMD ["uvicorn", "main:server", "--host", "0.0.0.0", "--port", "8060 "]