FROM python:3.9-slim-buster

ENV APP_NAME=api
ENV LABEL=latest

RUN apt update -y && apt install -y uvicorn

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]